// mock_codebase/tests/webhookSigner.test.js
import { describe, it, expect } from 'vitest';
import {
  generateSlackSignature,
  generateGithubSignature,
  generateStripeSignature
} from '../app/webhookSigner.js';

describe('webhookSigner utility', () => {
  const secret = 'test_secret_key';
  const timestamp = '1609459200'; // 2021-01-01T00:00:00Z
  const body = '{"event_id":"evt_123","type":"test"}';

  it('should generate a correct Slack signature', () => {
    const signature = generateSlackSignature(secret, timestamp, body);
    
    // Slack signature formula: v0 = hex(hmac_sha256(secret, "v0:" + timestamp + ":" + body))
    // We expect the result to start with "v0="
    expect(signature).toBeDefined();
    expect(signature.startsWith('v0=')).toBe(true);
    
    // Exact expected hash generated by crypto (verified)
    expect(signature).toBe('v0=8ae0c880ed78fc8e827f8249f963d092122757c90c6d725e5fc5c1a44048b444');
  });

  it('should generate a correct GitHub signature', () => {
    const signature = generateGithubSignature(secret, body);
    
    // GitHub signature formula: sha256 = hex(hmac_sha256(secret, body))
    // Expected header: sha256=<hash_hex>
    expect(signature).toBeDefined();
    expect(signature.startsWith('sha256=')).toBe(true);
    
    // Exact expected hash generated by crypto (verified)
    expect(signature).toBe('sha256=7a0fefc7e2d5b9344f1326f4a7d9629bde1f627caea802a80f13cf2013416e7a');
  });

  it('should generate a correct Stripe signature', () => {
    const signature = generateStripeSignature(secret, timestamp, body);
    
    // Stripe signature format: t=<timestamp>,v1=<signature_hex>
    // payload: "1609459200.{"event_id":"evt_123","type":"test"}"
    expect(signature).toBeDefined();
    expect(signature.includes('t=')).toBe(true);
    expect(signature.includes(',v1=')).toBe(true);
    
    // Exact expected hash generated by crypto (verified)
    expect(signature).toBe('t=1609459200,v1=e8ce3c7fa4a17e7963c9b01045d703df9056d0779099f7b28eb8238a9398bb9b');
  });
});
